name: CI-windows

on: [push]

jobs: 
    build-WINDOWS:

        runs-on: windows-latest

        steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
            settings-path: ${{ github.workspace }} # location for the settings.xml file


        - name: Setup Maven
          run: choco install maven

        - name: Setup MySQL
          run: |
            choco install mysql --params="'/QUIET /NORESTART'"
            mysql -u root -e "CREATE DATABASE voolmed_api;"

        - name: Build and Run the Project
          run: |
            cd /.github
            mvn clean install
            java -jar target/api-0.0.1-SNAPSHOT.jar.original
